### ISSUE TITLE
Trying to setup a test mail server.

### ISSUE THREAD

**Issue by bucaran** [sebastien/monitoring#30]
I want to write a python script that monitors a server list and emails an specified recipient(s) based in data collected from these servers (hard disk capacity, server load, etc). It looks like monitoring has a wider scope than my project, but I think I am on the right track looking at this project.

Actually I have a general idea about how to do some of these tasks, including sending email with python (yes), but I am unable to setup a email server on my local machine for testing sending/receiving emails.

I have been following several `postfix` [configuration](http://blog.anupamsg.me/2012/02/14/enabling-postfix-for-outbound-relay-via-gmail-on-os-x-lion-11/) [tutorials](http://blog.y3xz.com/blog/2012/01/11/configuring-postfix-to-work-with-gmail-on-mac-os-x) to no avail. I also looked at [some SO questions][1] dealing with Yosemite specific updates to some of the aforementioned tutorials, but still no luck.

Do you guys have any tips or recommendations?

### What I have tried...

Although, I just want to be able to send email via localhost for testing, for starters, I tried setting up `postfix` for gmail. Here is the relevant part of my `/etc/postfix/main.conf`:

    675 relayhost = smtp.gmail.com:587
    676 smtp_sasl_auth_enable = yes
    677 smtp_sasl_password_maps = hash:/etc/postfix/sasl_passwd
    678 smtp_sasl_security_options = #noanonymous
    679 smtp_use_tls = yes
    680 smtp_sasl_mechanism_filter = plain
    681 
    682 smtp_tls_security_level=encrypt
    683 tls_random_source=dev:/dev/urandom

After reloading `postfix`, I tried sending some dummy emails like:

    tree | mail -s "Hi" "jbuc...@gmail.com"

This is what `mailq` logs:

    B83E0EFDD0      828 Wed Mar  4 22:56:05  $USER@$HOSTNAME
                                                    (unknown mail transport error)
                                             jbuc...@gmail.com
    
    B87C6EE74B      282 Wed Mar  4 21:42:27  $USER@$HOSTNAME
    (delivery temporarily suspended: local data error while talking to smtp.gmail.com[74.125.203.108])

  [1]: http://stackoverflow.com/questions/26447316/mac-os-x-10-10-yosemite-postfix-sasl-authentication-failed

**Comment by sebastien** [comment]
Hi! You probably should ask on a linux administration forum, or, in your case use gmail as SMTP. Configuring an email server is actually quite hard, if you want to do it properly. 

There's actually an `Email` action in monitoring that allows to do just that:

```python
#!/usr/bin/env python
from monitoring import *
action = Email(
	"sebastien@ffctn.com",
	"[Monitoring] Test", "Sample message", 
	SMTP_SERVER,SMTP_USER,SMTP_PASSWORD
)
Monitor(
	Service(
		name = "test-action-email",
		monitor = (
			Fail   (Time.s(10), actions=action),
			Succeed(Time.s(10), actions=action)
		)
	)
).run()
```

Just define the `SMTP_*` variables and you're ready to go.

**Comment by bucaran** [comment]
Thanks, I will check this out.

Do you know if it's even possible to set up a mock server to send / receive email to / from localhost? My servers already have an email server configured (using sendmail), but I would like to setup one locally on my OS X.

Anyway, thanks!
