### ISSUE TITLE
error: file '/home/hgj/software/monitoring/Scripts/monitoring' does not exist

### ISSUE THREAD

**Issue by heartbeat2015** [sebastien/monitoring#34]
this error came up when I run python3 setup.py install.
Scripts dir is exactly not exist

**Comment by heartbeat2015** [comment]
just delete the Scrpit's line in setup.py

**Comment by sebastien** [comment]
Thanks a lot for reporting, I just fixed it and released `0.9.2` https://pypi.org/project/monitoring/#history with the fix.
